# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatREst' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Socket.IO-Client-Swift'

  # Pods for ChatREst

  target 'ChatREstTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatREstUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
